terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "6.0.0"
    }
    # The random provider is used to generate random values, such as passwords or unique identifiers
    # It is often used in conjunction with other resources to ensure that certain attributes are unique or
    # randomly generated.
    # For example, you might use the random provider to generate a random password for an AWS
    random = {
      source = "hashicorp/random"
      version = "3.7.2"
    }
  }
}


provider "aws" {
  # Configuration options
 region = "eu-north-1"
}

resource "aws_s3_bucket" "mybucket1" {
  bucket = "mybucketdemo${random_id.r_id.hex}" # r.id is the block name of the resource "random_id"  #"mybucketdemo" is a static name for the bucket, and the random_id.r_id.hex
  # r_id.hex is a random hexadecimal string generated by the random_id resource.
  # This ensures that the bucket name is unique across all AWS accounts.
}

  resource "aws_s3_object" "bucket-data2" {
  bucket = aws_s3_bucket.mybucket1.bucket
  # The source file to upload to the S3 bucket
  source = "../s3files/testfile.txt"
  # If the file is kept in some other directory then use the relative path from the current module
  # For example, if the file is in a subdirectory called s3files, use ./s3files/testfile.txt
  key = "/new-folder/mydata1.txt"
  #key is the name of the file in the S3 bucket and in this case it will create a new folder
  # and put the file in that folder
}


#random_id

resource "random_id" "r_id" {

  # The random_id resource generates a random value that can be used in other resources.
  # It is often used to create unique identifiers or random strings.
  byte_length = 8
}


